### ISSUE TITLE
Update all components to Origami v2

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#110]
This is an issue to track the progress of converting all our components to the new version of the specification which requires component be on npm and not on bower.

I've gone through our components and created a dependency graph which was used to create the phases below.

The phases go from the components which have no dependencies on other components (phase 1) to the components which have the deepest dependency graphs (phase 5).

Here is a list of steps to complete for a component -- https://gist.github.com/notlee/8338b043e26ae3cd9c1f0878e1e6ce7c

Phase 1:
- [x] o-brand - https://github.com/Financial-Times/o-brand/pull/84
- [x] ft-date-format - https://github.com/Financial-Times/ft-date-format/pull/96
- [x] o-errors - https://github.com/Financial-Times/o-errors/pull/116
- [x] ftdomdelegate - https://github.com/Financial-Times/ftdomdelegate/pull/172/files
- [x] ~o-layers~ - not being migrated!
- [x] ~n-map-content-to-topper~ - not an origami component!
- [ ] o-ads-embed - talk to ads
- [x] o-autoinit - https://github.com/Financial-Times/o-autoinit/pull/130
- [x] o-lazy-load - https://github.com/Financial-Times/o-lazy-load/pull/65
- [x] ~o-permutive~ - ads monorepo
- [x] o-test-component - https://github.com/Financial-Times/o-test-component/pull/66

Phase 2:
- [x] ~o-assets~ - not being migrated! 
- [x] o-colors - https://github.com/Financial-Times/o-colors/pull/300
- [x] fticons - https://github.com/Financial-Times/fticons/pull/134
- [x] o-date - https://github.com/Financial-Times/o-date/pull/169

Phase 3:
- [x] o-utils - https://github.com/Financial-Times/o-utils/pull/66
- [x] o-syntax-highlight - https://github.com/Financial-Times/o-syntax-highlight/pull/82
- [x] ~superstore-sync~ - not an origami component!
- [x] o-grid - https://github.com/Financial-Times/o-grid/pull/281
- [x] o-normalise - https://github.com/Financial-Times/o-normalise/pull/100
- [x] o-icons - https://github.com/Financial-Times/o-icons/pull/172
- [x] o-spacing - https://github.com/Financial-Times/o-spacing/pull/77
- [x] o-loading - https://github.com/Financial-Times/o-loading/pull/107
- [x] o-fonts - https://github.com/Financial-Times/o-fonts/pull/185

Phase 4:
- [x] o-visual-effects - https://github.com/Financial-Times/o-visual-effects/pull/75
- [x] o-toggle - https://github.com/Financial-Times/o-toggle/pull/83
- [ ] ~ads-config~ - not an origami component!
- [x] o-viewport - https://github.com/Financial-Times/o-viewport/pull/129
- [x] o-typography - https://github.com/Financial-Times/o-typography/pull/308
- [x] o-ft-affiliate-ribbon - https://github.com/Financial-Times/o-ft-affiliate-ribbon/pull/70
- [ ] g-audio - https://github.com/Financial-Times/g-audio/pull/16
- [ ] n-sliding-popup

Phase 5:
- [ ] o-ads
- [x] o-footer - https://github.com/Financial-Times/o-footer/pull/172
- [x] o-expander - https://github.com/Financial-Times/o-expander/pull/132
- [ ] n-notification
- [x] o-buttons - https://github.com/Financial-Times/o-buttons/pull/299
- [x] o-video - https://github.com/Financial-Times/o-video/pull/207
- [x] o-audio - https://github.com/Financial-Times/o-audio/pull/62
- [x] o-meter - https://github.com/Financial-Times/o-meter/pull/76
- [x] o-big-number - https://github.com/Financial-Times/o-big-number/pull/78
- [x] o-teaser-collection - https://github.com/Financial-Times/o-teaser-collection/pull/91
- [x] o-share - https://github.com/Financial-Times/o-share/pull/219
- [x] o-tracking - https://github.com/Financial-Times/o-tracking/pull/337
- [x] o-overlay (remember to remove o-layers!!) - https://github.com/Financial-Times/o-overlay/pull/274
- [x] o-stepped-progress - https://github.com/Financial-Times/o-stepped-progress/pull/71
- [x] o-footer-services - https://github.com/Financial-Times/o-footer-services/pull/81
- [x] o-forms - https://github.com/Financial-Times/o-forms/pull/396
- [x] o-editorial-typography - https://github.com/Financial-Times/o-editorial-typography/pull/84

Phase 6:
- [x] o-header - https://github.com/Financial-Times/o-header/pull/434
- [x] o-header-services - https://github.com/Financial-Times/o-header-services/pull/228
- [x] o-cookie-message - https://github.com/Financial-Times/o-cookie-message/pull/152
- [ ] o-crossword
- [x] o-subs-card - https://github.com/Financial-Times/o-subs-card/pull/82
- [x] o-message - https://github.com/Financial-Times/o-message/pull/158
- [x] o-tooltip - https://github.com/Financial-Times/o-tooltip/pull/163
- [x] o-banner - https://github.com/Financial-Times/o-banner/pull/144
- [x] o-table - https://github.com/Financial-Times/o-table/pull/249
- [x] o-comments - https://github.com/Financial-Times/o-comments/pull/208
- [x] o-quote - https://github.com/Financial-Times/o-quote/pull/95
- [x] o-topper - https://github.com/Financial-Times/o-topper/pull/92
- [x] o-labels - https://github.com/Financial-Times/o-labels/pull/118
- [x] o-tabs - https://github.com/Financial-Times/o-tabs/pull/138

Phase 7:
- [x] o-layout - https://github.com/Financial-Times/o-layout/pull/192
- [x] o-teaser - https://github.com/Financial-Times/o-teaser/pull/208
- [x] o-editorial-layout - https://github.com/Financial-Times/o-editorial-layout/pull/50
